<div id="sidebar-left"> 
    <div class="row">
        <ul id="sub-nav" class="convertion-apps">
            <li>
                <ul>
                    <li>
                        <a class="menu-title"><b><?php echo $this->translate('Conversion Apps') ?></b></a>
                    </li> 
                    <li>
                        <a class="active" href="#"><span class="gift icon"></span><?php echo $this->translate('Overview') ?></a>
                    </li> 
                </ul>
            </li>
        </ul>
    </div> 
</div>
<div id="content" class="fixed-width"> 
    <div id="content-inner"> 
        <ul class="breadcrumb"> 
            <li><a href="#"><?php echo $this->translate('Convertion Apps') ?></a> <span class="right-arrow"></span></li> 
            <li><a href="#"><?php echo $this->translate('Directory') ?></a> <span class="right-arrow"></span></li> 
            <li><?php echo $this->translate('Voucher Incentives') ?></li> 
        </ul>   
        <p class="h-space-1"></p>
        <div class="row">
            <img width="100%" height="160px" src="/images/voucher_incentives.png" />
        </div>
        <br>
        <br>
        <div class="content-left-conversion" style="float: left;">
            <img src="/images/voucher_gift.gif" />
        </div>
        <div class="content-right-convertion">
            <div style="float: left;">
                <h2><?php echo $this->translate('Voucher Incentives') ?></h2>
                <p><b><?php echo $this->translate('Profile your usersin real time and increase<br/> concersion rate by showing smart incentives') ?></b></p>
            </div>
            <div style="float: right;">
                <p><b><?php echo $this->translate('Provider:') ?></b> ConversionWunder</p>
                <a class="green" href="#"><?php echo $this->translate('Start Campaign') ?></a>
            </div>
            <div class="clear"></div>
            <div>
                <br>
                <?php echo $this->translate('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.') ?>
            </div>
        </div>
        <div class="clear"></div>
        <br>
        <br>
        <br>
        <div>
            <img src="/images/10_rabbit.gif" />
            <img src="/images/markt24.gif" style="float: right;" />
        </div>        
    </div>
</div> 
<div class="clear"></div>