    <div id="content-inner"> 
        <?php
        $title = $this->translate('Login User');
        $this->headTitle($title);
        ?>
        <h1><?php echo $this->escapeHtml($title) ?></h1>
        <?php
        $form = $this->form;
        $form->setAttribute('action',$this->url('user',array('action'=>'login')));
        $form->prepare();
        ?>
            <?php echo $this->form()->openTag($form) ?>
            <dl class="zend_form">
            <?php foreach ($form as $element): ?>
                <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
                    <dt><?php echo $this->formLabel($element) ?></dt>
                <?php endif ?>
                <?php if ($element instanceof Zend\Form\Element\Button): ?>
                    <dd><?php //echo $this->formButton($element) ?></dd>
                <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                    <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
                <?php else: ?>
                    <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
                <?php endif ?>
            <?php endforeach ?>
            </dl>
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
