<div id="sidebar-left"> 
    <div class="row"> 
        <ul id="sub-nav" class="without-icons">
            <li>
                <a class="active" href="<?php echo $this->url('user', array('action' => 'register')) ?>"><?php echo $this->translate('Register') ?></a>
            </li> 
        </ul>
    </div> 
</div>
<div id="content" class="fixed-width"> 
    <div id="content-inner"> 
        <h1>Register</h1>

        <?php
        $form = $this->registerForm;
        //print_r($form->get('name'));
        $form->setAttribute('action',$this->url('user',array('action'=>'register')));
        $form->prepare();

        //$form->prepare();
        //$form->setAttribute('action', $this->url('user/register'));
        ?>

        <?php echo $this->form()->openTag($form) ?>
            <dl class="zend_form">
                <dt><?php echo $this->formLabel($form->get('name_first')); ?></dt>
                <dd><?php echo $this->formInput($form->get('name_first')) . $this->formElementErrors($form->get('name_first')) ?></dd>

                <dt><?php echo $this->formLabel($form->get('name_last')); ?></dt>
                <dd><?php echo $this->formInput($form->get('name_last')) . $this->formElementErrors($form->get('name_last')) ?></dd>

                <dt><?php echo $this->formLabel($form->get('company')); ?></dt>
                <dd><?php echo $this->formInput($form->get('company')) . $this->formElementErrors($form->get('company')) ?></dd>

                <dt><?php echo $this->formLabel($form->get('domain')); ?></dt>
                <dd><?php echo $this->formInput($form->get('domain')) . $this->formElementErrors($form->get('domain')) ?></dd>

                <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
                <dd><?php echo $this->formInput($form->get('email')) . $this->formElementErrors($form->get('email')) ?></dd>

                <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
                <dd><?php echo $this->formInput($form->get('password')) . $this->formElementErrors($form->get('password')) ?></dd>

                <dt></dt>
                <dd><?php echo $this->formInput($form->get('submit')); ?></dd>

            </dl>
        <?php echo $this->form()->closeTag() ?>
    </div>
    
    <?php echo $this->partial('login',array('form'=>$loginForm)); ?>
</div> 
<div class="clear"></div>
