<?php
use Zend\Authentication\AuthenticationService;
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/def.css')
                        
                       /* ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') */ ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/def.js') ?>
    </head>
    <body>
        <div id="header-wrapper">
            <div id="header">
                <div class="logo">
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('ConversionWunder') ?></a>
                </div> 
            </div>
            <div class="clear"></div>
            <div class="nav-wrapper">
                <ul id="nav">
                    <li id="nav-logo"><a href="/">ConversionWunder</a></li> 
                    <!-- <li class="<?php echo $this->ControllerName() == "Application\Controller\Index" && $this->ActionName() == "index"?"active":""; ?>"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li> -->
                    <?php
                    $auth = new AuthenticationService;
                    if ($auth->hasIdentity()):
                        $idettity = $auth->getIdentity();
                        ?>
                        <li class="<?php echo ( $this->ControllerName() == "Project\Controller\Project" || $this->ControllerName() == "Project\Controller\Goal" || $this->ControllerName() == "Project\Controller\Site") ? "active" : ""; ?>"><a href="<?php echo $this->url('project',array('action'=>'index')) ?>"><?php echo $this->translate('Projects') ?></a></li>
                        <li class="<?php echo $this->ControllerName() == "Application\Controller\Conversions" ? "active" : ""; ?>"><a href="<?php echo $this->url('conversions',array('action'=>'index')) ?>"><?php echo $this->translate('Conversion Apps') ?></a></li>
                        <li class="<?php echo $this->ControllerName() == "User\Controller\Billing" ? "active" : ""; ?>"><a href="<?php echo $this->url('billing',array('action'=>'overview')) ?>"><?php echo $this->translate('Billing') ?></a></li>
                        <li class="<?php echo $this->ControllerName() == "User\Controller\User" ? "active" : ""; ?>"><a href="<?php echo $this->url('user',array('action'=>'account')) ?>"><?php echo $this->translate('Account') ?></a></li>
                    </ul>
                    <div class="logout"><a href="<?php echo $this->url('user',array('action'=>'logout')) ?>"><?php echo $this->translate('Logout') ?></a></div>
                    <div class="username"><a href="javascript: void(0)"><?php echo $idettity->email; ?></a></div>
                <?php else: ?>
                    <li class="<?php echo $this->ControllerName() == "User\Controller\User" && $this->ActionName() == "register"?"active":""; ?>"><a href="<?php echo $this->url('user',array('action'=>'register')) ?>"><?php echo $this->translate('Register') ?></a></li>
                    </ul>
                    <div class="login"><a href="<?php echo $this->url('user',array('action'=>'login')) ?>"><?php echo $this->translate('Login') ?></a></div>
                <?php endif; ?>
                <div class="clear"></div>
            </div>
        </div><!--/#header -->
        <div id="content-wrapper">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <div id="footer">
                <div class="copyright">Copyright &copy; 2012 ConversionWunder</div>
                <div class="clear"></div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>