	<div id="main-content"> <!-- Main Content Section with everything -->
			<noscript> <!-- Show a notification if the user has disabled javascript -->
				<div class="notification error png_bg">
					<div>
						Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
					</div>
				</div>
			</noscript>
			
			<!-- Page Head -->
			<h2><?php echo $this->escape($this->title); ?></h2>
			<p id="page-intro"><?php echo $this->subTitle ?></p>

			<div class="clear"></div> <!-- End .clear -->
			
			<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Users List</h3>
					
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
					
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
						
<!--					<div class="notification attention png_bg">
							<a href="#" class="close"><img src="/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
							<div>
								Hay nuevos Siniestros Recepcionados.
							</div>
						</div>
-->						<table>
							<thead>
							<tr>
								<th>Case Number</th>
								<th>Action</th>
							</tr>
							</thead>
							
							<tbody>
							<?php
							 if(count($this->paginator) != 0):	
								 foreach($this->paginator as $record): 
							 ?>
							<tr>
								<td><?php echo $record["case_number"] ?></td>
								<td><a href="<?php echo $this->url(array("action"=>"assign-to-inspector","id"=>$record["id"],"page"=>"")) ?>">Assign To Inspector</a></td>
							</tr>
							<?php
								 endforeach; 
							  else:
							 ?>
								<tr>
									<td colspan="2">No Case Found</td>
								</tr>
							 <?php
							  endif;	 
							 ?>
							</tbody>
							<?php echo $this->paginationControl($this->paginator,'Sliding','paginaton.phtml') ?>
							
							
						</table>
						
					</div> <!-- End #tab1 -->
					
					
				</div> <!-- End .content-box-content -->
				
			</div> <!-- End .content-box -->
			
			<div class="clear"></div>
			
			<div id="footer">
				<small>
						&#169; 2010 <a href="http://www.smartic.cl" target="_blank">Smartic</a> | <a href="#">Arriba</a>
				</small>
			</div><!-- End #footer -->
			
		</div> <!-- End #main-content -->


