<script language="javascript">
    $(document).ready(function(){
        $("#sites").change(function(){
            var id = $("#sites option:selected").val();
            var url = '<?php echo $this->url('billing',array('action'=>'buy-credits','id'=>'--id--')); ?>';
            window.location.href = url.replace('--id--',id);
        })
    });
</script>
<div id="sidebar-left"> 
    <div class="row"> 
        <ul id="sub-nav" class="without-icons">
            <li>
                <a class="<?php echo $this->ControllerName() == "User\Controller\Billing" && $this->ActionName() == "overview" ? "active" : ""; ?>" href="<?php echo $this->url('billing', array('action' => 'overview')) ?>"><?php echo $this->translate('Overview') ?></a>                                      
            </li> 
            <li> 
                <a class="<?php echo $this->ControllerName() == "User\Controller\Billing" && $this->ActionName() == "detail" ? "active" : ""; ?>" href="<?php echo $this->url('billing', array('action' => 'detail')) ?>"><?php echo $this->translate('Billing Details') ?></a>
            </li> 
            <li> 
                <a href="#"><?php echo $this->translate('Invoices') ?></a>
            </li> 
            <li> 
                <a class="<?php echo $this->ControllerName() == "User\Controller\Billing" && $this->ActionName() == "buy-credits" ? "active" : ""; ?>" href="<?php echo $this->url('billing', array('action' => 'buy-credits')) ?>"><?php echo $this->translate('Selected Plan') ?></a>
            </li> 
        </ul> 
    </div> 
</div>
<div id="content" class="fixed-width"> 
    <div id="content-inner">
         <?php
            $form->setAttribute('action',$this->url('billing',array('action'=>'buy-credits', 'id'=>$siteId)));
            $form->prepare();
            echo $this->form()->openTag($form)
        ?>
        <ul class="breadcrumb"> 
            <li><a href="#"><?php echo $this->translate('Billing') ?></a> <span class="right-arrow"></span></li> 
            <li><?php echo $this->translate('Overview') ?></li> 
        </ul>   
        <p class="h-space-1"></p>
        <div>                
            <h2><?php echo $this->translate('Buy Credits') ?></h2>
        </div>
        <div class="content-row">
                <div class="content-row-left">
                        <?php echo $this->translate('Select Site') ?>
                </div>
                <div class="content-row-right">
                        <select id="sites">
                        <?php foreach($sites as $site): ?>
                            <?php foreach($site as $record): ?>
                                <option <?php echo $record->id==$siteId?"selected='selected'":"";  ?> value="<?php echo $record->id ?>"><?php echo$record->domain; ?></option>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                        </select>
                </div>
        </div>
        <p class="h-space-1"> </p>
        <div class="h-line"> </div>
        <p class="h-space-1"> </p>
        <div>                
                <h2><?php echo $this->translate('Select a plan') ?></h2>
        </div>
        <table class="table table-bordered">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('*1000 Credits per month') ?></th>
                        <th><?php echo $this->translate('*5000 Credits per month') ?></th>
                        <th><?php echo $this->translate('*25000 Credits per month') ?></th>
                        <th><?php echo $this->translate('*50000 Credits per month') ?></th>
                        <th><?php echo $this->translate('*100000 Credits per monthnd and more') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $this->translate('100 £ ') ?></td>
                        <td><?php echo $this->translate('475 £ ') ?></td> 
                        <td><?php echo $this->translate('2250 £ ') ?></td> 
                        <td><?php echo $this->translate('4250 £ ') ?></td>
                        <td><?php echo $this->translate('contact sales ') ?></td>
                   </tr>
                    <tr>
                        <td><?php echo $this->translate('20,000 unique users') ?></td>
                        <td><?php echo $this->translate('100,000 unique users') ?></td>
                        <td><?php echo $this->translate('500,000 unique users') ?></td>
                        <td><?php echo $this->translate('1,000,000 unique users') ?></td>
                        <td><?php echo $this->translate('2,000,000 unique users and more') ?></td>
                        

                    </tr>
                    <tr>
                        <td></td>
                        <td><?php echo $this->translate('5% discount') ?></td>
                        <td><?php echo $this->translate('10% discount') ?></td>
                        <td><?php echo $this->translate('15% discount') ?></td>
                        <td></td>

                    </tr>

                    <tr>
                        <td><input type="radio" name="plan_id" value="7" <?php echo empty($credit)||$credit->planId==7?"checked='checked'":""; ?>  /><?php echo $this->translate('Select Plan') ?></td>
                        <td><input type="radio" name="plan_id" value="17" <?php echo !empty($credit)&&$credit->planId==17?"checked='checked'":""; ?> /><?php echo $this->translate('Select Plan') ?></td>
                        <td><input type="radio" name="plan_id" value="27" <?php echo !empty($credit)&&$credit->planId==27?"checked='checked'":""; ?> /><?php echo $this->translate('Select Plan') ?></td>
                        <td><input type="radio" name="plan_id" value="37" <?php echo !empty($credit)&&$credit->planId==37?"checked='checked'":""; ?> /><?php echo $this->translate('Select Plan') ?></td>
                        <td><a href="#" class="green">Contact sales</a></td>
                    </tr>
                </tbody>
            </table>

            <p><?php echo $this->translate('<b> No contracts! </b> ConvsionWunder is a pay-as-you-go service. Pay month-to-month, and 
                if you decide to cancel, youll be billed for the current month, but you wont be biled again ') ?><br />
            <?php echo $this->translate('<b> Credits expire! </b> by the end of every month') ?><br />
           </p>
            
        <p class="h-space-1"> </p>
        <div class="h-line"> </div>
        <p class="h-space-1"> </p>
        <div>                
                <h2><?php echo $this->translate('Payment Type') ?></h2>
        </div>
        <div class="content-row">
            <div class="content-row-left">
                <?php echo $this->translate('Invoice') ?>
            </div>
            <div class="content-row-right-double">
                <input type="radio" name="invoice" checked="checked" value="invoice" />
            </div>
        </div>
        <?php echo $this->partial('billing/_form',array('form'=>$form)); ?>  
        <?php echo $this->form()->closeTag() ?>
    </div>
</div> 
<div class="clear"></div>